### ISSUE TITLE
[BUG] RealTime throwing errors, not syncing real time to game time.

### ISSUE THREAD

**Issue by singlekeycap** [Minecon724/RealWeather#2]
### System Info
**Minecraft Version:** 1.20.1 (PaperMC Build 169)
**Java Version:** OpenJDK 64-Bit 18.0.2 | OpenJDK 64-Bit 17.0.8 (happens on both versions)
**Host OS:** Ubuntu Server 23.04 (amd64)  |  **Kernel:** 6.2.0-27
**RealTime Config:**
```
realtime:
  enabled: true
  worlds:
  - world
  timezone: 'auto'
  timeScale: 1.0
  interval: 5
```

### Error Info
**Steps to Reproduce:** 
1. Enable RealTime with the settings above
2. Start the server
3. Profit...?

**Logs:**
```
[17:52:24 WARN]: [RealWeather] Plugin RealWeather v0.4.0 generated an exception while executing task 4
java.lang.IllegalStateException: TimeSkipEvent may only be triggered synchronously.
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42) ~[paper-1.20.1.jar:git-Paper-134]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-134]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.setFullTime(CraftWorld.java:868) ~[paper-1.20.1.jar:git-Paper-134]
        at pl.minecon724.realweather.realtime.RTTask.run(RTTask.java:34) ~[realweather-0.4.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-134]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-134]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
^ basically just this over and over

Honestly, I've never done Java before. Looking through your code and the "compiled" version, I don't see how it would be calling TimeSkipEvent. Either way, let me know if you need more info.

**Comment by Minecon724** [comment]
fixed, download from spigot:
https://www.spigotmc.org/resources/realweather-realtime.101599/update?update=514930

please note this plugin is abandoned so i may not patch future issues
thanks for reporting

**Comment by singlekeycap** [comment]
Great, thanks! I might learn Java and fork it in the future then
