### ISSUE TITLE
How do I verify that the plugin is working?

### ISSUE THREAD

**Issue by TheRealGuruJoe** [Minecon724/RealWeather#4]
Hello there!
It is easy to verifry if the Real Time part is working. 
I made an account on OpenWorldmap and changed my API key. 
I also made a profile on Geolite2 and changed my account ID and API Key there too.

Now I'm not quite sure if everything is working properly. Is there a quick way to verify that?

Thanks a lot!

Server: Spigot, 1.20.4

**Comment by Minecon724** [comment]
append `logging: true` with no leading spaces or tabs to config.yml
no other way currently

**Comment by TheRealGuruJoe** [comment]
Thank you. How often does the Plugin update the current weather?

**Comment by Minecon724** [comment]
every 1 minute

**Comment by TheRealGuruJoe** [comment]
I'm currently on this server. I set the location to Dubai, because I now that it's sunny there.
I set the weather to rainy.
Shouldn't the Plugin change the weather to sunny sooner or later?

Also I don't receive any errors while starting the server.

**Comment by Minecon724** [comment]
send logs

**Comment by TheRealGuruJoe** [comment]
The plugin tells me that it changes time, wich makes sense.
It also tells me it loaded succesfully, but no matter how long I wait, the weather doesn't change. 

I tried adding "logging: true", but it just doesn't log anything.

**Comment by Minecon724** [comment]
look for world loading messages from the plugin, if there's none you didn't modify the config correctly, make sure that line has no leading spaces and restart your server

**Comment by TheRealGuruJoe** [comment]
I uploaded the config.yml file to MediaFire if you want to take a look at it. 
I'm not sure what I did wrong.

https://www.mediafire.com/folder/0mu5q7jgub2q5/stuff

**Comment by Minecon724** [comment]
your config is fine, are you looking at the console?

**Comment by TheRealGuruJoe** [comment]
Yes, I do. I can see that Real Weather starts up like normal, loads 2 packages and eventually starts changing time.
Everytime it does change the time, I get a message in the console.
But there is never a message that tells me it tried to change the weather. 

Although it tells me it changed the weather to clear while startup, it's still rainy after that.

**Comment by TheRealGuruJoe** [comment]
I'm not sure if there is any personal information hidden in the startup process, but I'll just copy it here:


Unbundling libraries to /home/joel/Spigot_Server/bundler
Starting server
Loading libraries, please wait...
[10:37:14] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[10:37:15] [ServerMain/INFO]: Loaded 7 recipes
[10:37:14] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[10:37:15] [ServerMain/INFO]: Loaded 7 recipes
[10:37:16] [Server thread/INFO]: Starting minecraft server version 1.20.4
[10:37:16] [Server thread/INFO]: Loading properties
[10:37:16] [Server thread/INFO]: This server is running CraftBukkit version 4090-Spigot-b754dcc-38b1f49 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)
[10:37:17] [Server thread/INFO]: Server Ping Player Sample Count: 12
[10:37:17] [Server thread/INFO]: Using 4 threads for Netty based IO
[10:37:17] [Server thread/INFO]: Debug logging is disabled
[10:37:17] [Server thread/INFO]: Default game type: CREATIVE
[10:37:17] [Server thread/INFO]: Generating keypair
[10:37:17] [Server thread/INFO]: Starting Minecraft server on *:25565
[10:37:17] [Server thread/INFO]: Using epoll channel type
[10:37:17] [Server thread/ERROR]: Could not load 'plugins/AreaShop.jar'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency Vault. Please download and install Vault to run this plugin.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:280) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:121) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:430) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:223) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:37:17] [Server thread/INFO]: [RealWeather] Loading 2 libraries... please wait
[10:37:17] [Server thread/INFO]: [RealWeather] Loaded library /home/joel/Spigot_Server/libraries/org/json/json/20231013/json-20231013.jar
[10:37:17] [Server thread/INFO]: [RealWeather] Loaded library /home/joel/Spigot_Server/libraries/com/maxmind/geoip2/geoip2/4.2.0/geoip2-4.2.0.jar
[10:37:17] [Server thread/INFO]: [AuthMe] Loading AuthMe v5.6.0-FORK-b48
[10:37:17] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.3.0+6678-55745ad
[10:37:18] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@3afcf189]
[10:37:18] [Server thread/INFO]: [CustomJoinMessages] Loading CustomJoinMessages v17.5.0
[10:37:18] [Server thread/INFO]: [TicketManager] Loading TicketManager v1.20.4.a.1
[10:37:18] [Server thread/INFO]: [RealWeather] Loading RealWeather v0.5.0.1
[10:37:18] [Server thread/INFO]: [CustomBansPlus] Loading CustomBansPlus v3.6
[10:37:18] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v7.0.9+5934e49
[10:37:18] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.3.0+6678-55745ad
[10:37:18] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[10:37:18] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[10:37:18] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R3.PaperweightAdapter as the Bukkit adapter
[10:37:19] [Server thread/INFO]: [WorldEdit] ====================================================
[10:37:19] [Server thread/INFO]: [WorldEdit]  WorldEdit works better if you use Paper
[10:37:19] [Server thread/INFO]: [WorldEdit]  as your server software. 
[10:37:19] [Server thread/INFO]: [WorldEdit]   
[10:37:19] [Server thread/INFO]: [WorldEdit]  Paper offers significant performance improvements,
[10:37:19] [Server thread/INFO]: [WorldEdit]  bug fixes, security enhancements and optional
[10:37:19] [Server thread/INFO]: [WorldEdit]  features for server owners to enhance their server.
[10:37:19] [Server thread/INFO]: [WorldEdit]   
[10:37:19] [Server thread/INFO]: [WorldEdit]  Paper includes Timings v2, which is significantly
[10:37:19] [Server thread/INFO]: [WorldEdit]  better at diagnosing lag problems over v1.
[10:37:19] [Server thread/INFO]: [WorldEdit]   
[10:37:19] [Server thread/INFO]: [WorldEdit]  All of your plugins should still work, and the
[10:37:19] [Server thread/INFO]: [WorldEdit]  Paper community will gladly help you fix any issues.
[10:37:19] [Server thread/INFO]: [WorldEdit]   
[10:37:19] [Server thread/INFO]: [WorldEdit]  Join the Paper Community @ https://papermc.io
[10:37:19] [Server thread/INFO]: [WorldEdit] ====================================================
[10:37:19] [Server thread/INFO]: [RealWeather] Enabling RealWeather v0.5.0.1
[10:37:19] [Server thread/INFO]: [RealWeather] [weather] done
[10:37:19] [Server thread/INFO]: [RealWeather] [weather] started
[10:37:19] [Server thread/INFO]: [RealWeather] RealWeather enabled! (240 ms)
[10:37:19] [Server thread/INFO]: Preparing level "world"
[10:37:19] [Server thread/INFO]: -------- World Settings For [world] --------
[10:37:19] [Server thread/INFO]: Mob Spawn Range: 6
[10:37:19] [Server thread/INFO]: Experience Merge Radius: 3.0
[10:37:19] [Server thread/INFO]: Max TNT Explosions: 100
[10:37:19] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:37:19] [Server thread/INFO]: Cactus Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: Cane Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: Melon Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: Sapling Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: Carrot Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: Potato Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: Wheat Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: Vine Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: Kelp Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[10:37:19] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[10:37:19] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64
[10:37:19] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[10:37:19] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[10:37:19] [Server thread/INFO]: View Distance: 24
[10:37:19] [Server thread/INFO]: Simulation Distance: 16
[10:37:19] [Server thread/INFO]: Item Despawn Rate: 6000
[10:37:19] [Server thread/INFO]: Item Merge Radius: 2.5
[10:37:19] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:37:19] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[10:37:19] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[10:37:19] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[10:37:20] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[10:37:20] [Server thread/INFO]: Mob Spawn Range: 6
[10:37:20] [Server thread/INFO]: Experience Merge Radius: 3.0
[10:37:20] [Server thread/INFO]: Max TNT Explosions: 100
[10:37:20] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:37:20] [Server thread/INFO]: Cactus Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: Cane Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: Melon Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: Sapling Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: Carrot Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: Potato Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: Wheat Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: Vine Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: Kelp Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[10:37:20] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[10:37:20] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64
[10:37:20] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[10:37:20] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[10:37:20] [Server thread/INFO]: View Distance: 24
[10:37:20] [Server thread/INFO]: Simulation Distance: 16
[10:37:20] [Server thread/INFO]: Item Despawn Rate: 6000
[10:37:20] [Server thread/INFO]: Item Merge Radius: 2.5
[10:37:20] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:37:20] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[10:37:20] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[10:37:20] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[10:37:20] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[10:37:21] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[10:37:21] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[10:37:21] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[10:37:21] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[10:37:22] [Worker-Main-3/INFO]: Preparing spawn area: 4%
[10:37:22] [Server thread/INFO]: Time elapsed: 2498 ms
[10:37:22] [Server thread/INFO]: [RealWeather] [weatherchanger] World world is loading
[10:37:22] [Server thread/INFO]: [RealWeather] [weatherchanger] World world has been registered
[10:37:22] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[10:37:23] [Worker-Main-7/INFO]: Preparing spawn area: 0%
[10:37:23] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[10:37:23] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[10:37:24] [Worker-Main-5/INFO]: Preparing spawn area: 99%
[10:37:24] [Server thread/INFO]: Time elapsed: 1503 ms
[10:37:24] [Server thread/INFO]: [RealWeather] [weatherchanger] World world_the_end is loading
[10:37:24] [Server thread/INFO]: [RealWeather] [weatherchanger] World world_the_end has been registered
[10:37:24] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.6.0-FORK-b48
[10:37:24] [Server thread/INFO]: [AuthMe] You are running an unofficial fork version of AuthMe!
[10:37:24] [Server thread/INFO]: [AuthMe] SQLite Setup finished
[10:37:24] [Server thread/INFO]: [AuthMe] No supported permissions system found! Permissions are disabled!
[10:37:24] [Server thread/INFO]: [AuthMe] 
    ___                 ___   
   /   |   / /_/ /_  /  |/  / 
  / /| |/ / / / /  \/ /|_/ / _ \
 / ___ / /_/ / /_/ / / / /  / /  /
/_/  |_\,_/\__/_/ /_/_/  /_/\___/ 
                                    
[10:37:24] [Server thread/INFO]: [AuthMe] AuthMeReReloaded is running on Spigot
[10:37:24] [Server thread/INFO]: [AuthMe] AuthMeReReloaded is enabled successfully!
[10:37:24] [Server thread/INFO]: [AuthMe] GitHub: https://github.com/HaHaWTH/AuthMeReReloaded/
[10:37:24] [Server thread/INFO]: [AuthMe] Checking for updates...
[10:37:24] [Server thread/INFO]: [CustomJoinMessages] Enabling CustomJoinMessages v17.5.0
[10:37:25] [Server thread/INFO]: [TicketManager] Enabling TicketManager v1.20.4.a.1
[10:37:25] [Server thread/INFO]: [TicketManager] TicketManager from TheTealViper initializing!
[10:37:25] [Server thread/INFO]: [CustomBansPlus] Enabling CustomBansPlus v3.6
[10:37:25] [Server thread/INFO]: v1_20_R3
[10:37:25] [Thread-10/INFO]: [CBP] Checking for updates...
[10:37:25] [Server thread/INFO]:  Vault plugin not found, baldeduct and offline ban/mute bypasses functions are disabled. Ban/mute bypass will ONLY WORK if the target player is ONLINE.
[10:37:25] [Server thread/INFO]: AuthMe plugin found.
[10:37:25] [Server thread/INFO]: Database Initialized.
[10:37:25] [Server thread/INFO]: [CustomBansPlus] Tables Initialized.
[10:37:25] [Server thread/INFO]: Save Cache Initiated
[10:37:25] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v7.0.9+5934e49
[10:37:25] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[10:37:25] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[10:37:25] [Server thread/INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
[10:37:25] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[10:37:25] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[10:37:25] [Server thread/INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[10:37:25] [Server thread/INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[10:37:25] [Server thread/INFO]: [WorldGuard] (world_the_end) Lava fire is PERMITTED.
[10:37:25] [Server thread/INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[10:37:25] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[10:37:25] [Server thread/INFO]: [WorldGuard] Loading region data...
[10:37:25] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:37:25] [Server thread/INFO]: Done (6.252s)! For help, type "help"
[10:37:25] [Server thread/INFO]: [RealWeather] [timer] Updated time for world (to 2623)
[10:37:26] [Server thread/INFO]: [RealWeather] [weatherchanger] new weather: CLEAR LIGHT
[10:37:26] [Craft Scheduler Thread - 2/WARN]: [AuthMe] New version available! Latest:b49 Current:b48
[10:37:26] [Craft Scheduler Thread - 2/WARN]: [AuthMe] Download from here: https://github.com/HaHaWTH/AuthMeReReloaded/releases/latest
[10:37:29] [Server thread/INFO]: [RealWeather] [timer] Updated time for world (to 2624)
[10:37:33] [Server thread/INFO]: [RealWeather] [timer] Updated time for world (to 2625)
[10:37:36] [Server thread/INFO]: [RealWeather] [timer] Updated time for world (to 2626)
[10:37:40] [Server thread/INFO]: [RealWeather] [timer] Updated time for world (to 2627)
[10:37:43] [Server thread/INFO]: [RealWeather] [timer] Updated time for world (to 2628)

**Comment by Minecon724** [comment]
this should work:
https://github.com/Minecon724/RealWeather/actions/runs/9242661874/artifacts/1538587432

**Comment by TheRealGuruJoe** [comment]
Well, now it changes the weather to clear correctly while startup, but still just this one time. After that, nothing weather-realted happens.

**Comment by Minecon724** [comment]
it polls owm every 1 minute, but if the weather hasn't changed it doesn't log anything

**Comment by TheRealGuruJoe** [comment]
Well, I set the weather to rain and then shut down the server. As the position is still Dubai, the weather changes to clear as soon as I start up the server. That makes sense so far.
But, when I now set the weather to rain, it should change back to clear after one minute, shouldn't it?
Well, it doesn't, now it stays on rainy.

**Comment by Minecon724** [comment]
it doesn't because the *real* weather has not changed - the plugin uses its own memory
this is if you want to temporarily take control like what you did
if you really need to see the change, wait or try the (cosmetical) `globe` mode

**Comment by TheRealGuruJoe** [comment]
Interesting. Thanks for your help!
